/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.model.Abbonamento;
import org.example.model.Articolo;
import org.example.model.Categoria;
import org.example.model.Prodotto;
import org.example.model.Servizio;
import org.example.services.Carrello;

public class App {
    public static void main(String[] args) {
        Carrello carrello = Carrello.getInstance();
        // Creazione articoli
        Articolo laptop = new Prodotto("Laptop", 1200.99, Categoria.ELETTRONICA);
        Articolo maglietta = new Prodotto("Maglietta", 19.99, Categoria.ABBIGLIAMENTO);
        Articolo abbonamentoStreaming = new Abbonamento("Netflix", 9.99, Categoria.SERVIZI);
        Articolo corsoOnline = new Servizio("Corso Java", 49.99, Categoria.SERVIZI);

        // Aggiunta articoli al carrello
        carrello.aggiungiArticolo(laptop);
        carrello.aggiungiArticolo(maglietta);
        carrello.aggiungiArticolo(abbonamentoStreaming);
        carrello.aggiungiArticolo(corsoOnline);

        // Stampa ordinata per prezzo
        System.out.println("Articoli ordinati per prezzo:");
        carrello.stampaArticoliOrdinatiPerPrezzo();

        // Stampa ordinata per categoria
        System.out.println("\nArticoli ordinati per categoria:");
        carrello.stampaArticoliOrdinatiPerCategoria();
    }
}
